### ISSUE TITLE
🤔disable property sorting

### ISSUE THREAD

**Issue by thisVioletHydra** [onigoetz/postcss-lightningcss#133]
Hello, I want to disable sorting in your plugin. How can I do that?

ORIGIN:
```css
.item {
  overflow: auto;
  cursor: pointer;
  text-decoration: none;
  grid: 37px / 37px 1fr;
  justify-content: stretch;
  align-items: center;
  gap: 0;
  padding-left: 0.5rem;
  display: grid;

  &:hover {
    background-color: var(--color-gray-50);
  }
}
```

postcssLightningcss

```css
.Cboard_aside_BoardMenuCard__item {
  cursor: pointer;
  grid: 2.3125rem/2.3125rem 1fr;
  justify-content: stretch;
  align-items: center;
  gap: 0;
  padding-left: .5rem;
  text-decoration: none;
  display: grid;
  overflow: auto;
}
```
